// <auto-generated />
using EFCrudUygulama2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCrudUygulama2.Migrations
{
    [DbContext(typeof(HayvanContext))]
    partial class HayvanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCrudUygulama2.Data.Hayvan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Hayvanlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Kedi"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Köpek"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Aslan"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Kuş"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
